name:                powerdeck
version:             0.0.0.0
github:              "flajann2/powerdeck"
license:             MIT
author:              "Fred Mitchell"
maintainer:          "fred.mitchell@gmx.de"
copyright:           "2021 Fred Mitchell"

extra-source-files:
- README.org
- ChangeLog.org

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

description:         Please see the README on GitHub at <https://github.com/flajann2/streamdeck-ui-hs#readme>

dependencies:
  - base >= 4.7 && < 5
  
library:
  source-dirs: src

executables:
#  test-glfw:
#    main:                test-glfw.hs
#    source-dirs:         examples
#    ghc-options:
#    - -threaded
#    - -rtsopts
#    - -with-rtsopts=-N
#    dependencies:
#    - powerdeck 
#    - hidapi
#    - dbus
#    - bytestring
#    - Yampa
#    - text
#    - OpenGL
#    - GLFW-b

  test-gui:
    main:                test-gui.hs
    source-dirs:         examples
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - powerdeck 
    - hidapi
    - dbus
    - bytestring
    - Yampa
    - gi-gtk
    - gi-gtk-declarative
    - haskell-gi-base
    - text
    - gi-gtk-declarative-app-simple
    
  test-hid:
    main:                test-hid.hs
    source-dirs:         examples
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - streamdeck-ui-hs
    - hidapi
    - dbus
    - bytestring
 
  test-dbus:
    main:                dbusdump.hs
    source-dirs:         examples
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - powerdeck
    - hidapi
    - dbus
   
  powerdeck:
    main:                Powerdeck-ui.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - powerdeck
    - dbus
    - bytestring
    - text
    - Yampa
    - gi-gtk
    - gi-gtk-declarative
    - gi-gtk-declarative-app-simple
    - haskell-gi-base
 
  powerdeck-daemon:
    main:                Powerdeck-daemon.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - powerdeck
    - hidapi
    - dbus

tests:
  streamdeck-ui-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - powerdeck
