name:                streamdeck-ui-hs
version:             0.0.0.0
github:              "flajann2/streamdeck-ui-hs"
license:             MIT
author:              "Fred Mitchell"
maintainer:          "fred.mitchell@gmx.de"
copyright:           "2021 Fred Mitchell"

extra-source-files:
- README.org
- ChangeLog.org

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

description:         Please see the README on GitHub at <https://github.com/flajann2/streamdeck-ui-hs#readme>

dependencies:
  - base >= 4.7 && < 5
  #- reflex
  
library:
  source-dirs: src

executables:
  test-gui:
    main:                test-gui.hs
    source-dirs:         examples
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - streamdeck-ui-hs
    - hidapi
    - dbus
    - bytestring
    - Yampa
    
  test-hid:
    main:                test-hid.hs
    source-dirs:         examples
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - streamdeck-ui-hs
    - hidapi
    - dbus
    - bytestring
 
  test-dbus:
    main:                dbusdump.hs
    source-dirs:         examples
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - streamdeck-ui-hs
    - hidapi
    - dbus
   
  streamdeck-ui:
    main:                Streamdeck-ui.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - streamdeck-ui-hs
    #- reflex
    - dbus
    #- fltkhs
    
  streamdeck-daemon:
    main:                Streamdeck-daemon.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - streamdeck-ui-hs
    #- reflex
    - hidapi
    - dbus

tests:
  streamdeck-ui-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - streamdeck-ui-hs
