#resolver: lts-17.2
resolver: lts-16.11

#allow-newer: true

packages:
- .

extra-deps:
  - wx-0.92.3.0
  - wxcore-0.92.3.0
  - reactive-banana-1.2.1.0
  - wxc-0.92.3.0
  - wxdirect-0.92.3.0
  - Cabal-1.24.2.0
  - binary-0.8.8.0
  - parsec-3.1.14.0
  - semigroups-0.18.5
  - text-1.2.4.1
  - hashable-1.2.7.0
#  - d-bus-0.1.8
