resolver: lts-18.0
#resolver: lts-17.2

allow-newer: true

packages:
  - .

extra-deps:
  - reflex-0.8.1.0
  - dbus-1.2.21
  - fltkhs-0.8.0.3
  - bytestring-0.10.12.0
  - Yampa-0.13.1
  - gi-gtk-declarative-0.7.0
  - gi-gtk-declarative-app-simple-0.7.0
