resolver: lts-17.2
#resolver: lts-16.11
#resolver: lts-13.19

allow-newer: true

packages:
- .

extra-deps:
  - reactive-banana-1.2.1.0
  - d-bus-0.1.8
  # dependencies
  - hashable-1.2.7.0
  - semigroups-0.18.5
