resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/16/28.yaml
#resolver: lts-12.26
#resolver: lts-13.11
#resolver: nightly-2018-05-30
#resolver: nightly-2021-01-05

packages:
- .

extra-deps:
  #- gi-gtk-declarative-0.6.3
  #- gi-gtk-declarative-app-simple-0.6.3
  - haskell-gi-0.24.7
  - haskell-gi-base-0.24.5
