#resolver:
#  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/16/28.yaml

#resolver: lts-17.2
resolver: lts-16.11
#resolver: nightly-2018-05-30
#resolver: nightly-2021-01-05

allow-newer: true

packages:
- .

extra-deps:
#  - wx-0.92.3.0
#  - wxcore-0.92.3.0
  - reactive-banana-1.2.1.0
#  - wxc-0.92.3.0
#  - wxdirect-0.92.3.0
#  - Cabal-1.24.2.0
#  - containers-0.5.11.0
#  - binary-0.8.8.0
#  - parsec-3.1.14.0
#  - process-1.4.3.0
  - semigroups-0.18.5
#  - text-1.2.4.1
#  - time-1.8.0.4
#  - directory-1.3.6.1
#  - unix-2.7.2.2
  - hashable-1.2.7.0
